version: '3.8'

services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - microservices-network

  service_registry:
    build: .
    container_name: service_registry
    depends_on:
      - consul
    env_file:
      - path: .env
        required: true
    ports:
      - "5000:5000"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
